name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ruby-version: ['3.2', '3.3']

    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Ruby ${{ matrix.ruby-version }}
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby-version }}
        bundler-cache: true
    
    - name: Run RuboCop
      run: bundle exec rubocop
    
    - name: Run tests
      run: bundle exec rspec
    
    - name: Generate documentation
      run: bundle exec yard doc
      if: matrix.ruby-version == '3.2'
    
    - name: Upload coverage to Qlty
      uses: qltysh/qlty-action/coverage@v1
      if: matrix.ruby-version == '3.2'
      with:
        token: ${{ secrets.QLTY_COVERAGE_TOKEN }}
        files: coverage/.resultset.json

